add babel loader
ShvetaJain/webpack pull request #2
Opened 2019-03-12 12:28 UTC by ShvetaJain

2019-03-12 12:56 UTC, abp437 requested changes
Need Changes.

2019-03-12 12:56 UTC, abp437 commented on webpack.config.js
>  };
Always add an extra line at the end of file.

2019-03-12 12:56 UTC, abp437 commented on app.js
> +const test = "vishal teacher";
Single quotes in js file.

2019-03-12 12:56 UTC, abp437 commented on .babelrc
> +"presets": ["es2015"]
Don't use this preset, instead use `env`, it has much wider support.

2019-03-12 12:56 UTC, abp437 commented on webpack.config.js
> +          test: [/\.js$/],
Add support even for `.jsx` files.

2019-03-13 01:12 UTC, visha12l commented on webpack.config.js
> +    },
1)add eslint loader 
2)use resolve from webpack https://webpack.js.org/configuration/resolve/
3)integration with codacy (its an hosted automated code review service) https://www.codacy.com/

2019-03-19 13:36 UTC, visha12l commented on src/app.js
> +  function test1() {
use es6 arrow functions

2019-03-19 13:39 UTC, visha12l commented on src/app.js
> +  function objectTest() {
use es6 arrow functions

2019-03-19 13:40 UTC, visha12l commented on src/app.js
> +  function destructure() {
use es6 arrow functions

2019-03-22 14:00 UTC, merged